export const products = [
    {
        id: '1',
        name: 'Xbox Series X',
        img: 'images/Microsoft-Xbox-Series-X.jpg',
        price: 499.99,
        category: 'consoles',
        stock: 6,
        description: 'Description of Xbox Series X',
        rating: 4.2,
        seller: 'Microsoft',
    },
    {
        id: '2',
        name: 'Playstation 5',
        img: 'images/Sony-PlayStation-5-Console.jpg',
        price: 499.99,
        category: 'consoles',
        stock: 2,
        description: 'Description of Playstation 5',
        rating: 4.8,
        seller: 'Sony',
    },
    {
        id: '3',
        name: 'Elden Ring',
        img: 'images/Elden-Ring-Steam.jpg', 
        price: 59.99,
        category: 'games',
        stock: 15,
        description: 'Description of Elden Ring',
        rating: 4.9,
        seller: 'Bandai',
    },
    {
        id: '4',
        name: 'Dark Souls Remastered',
        img: 'images/Dark-Souls-Remastered-Steam.jpg', 
        price: 39.99,
        category: 'games',
        stock: 12,
        description: 'Description of Dark Souls',
        rating: 4.1,
        seller: 'Bandai',
    },
    {
        id: '5',
        name: 'Minecraft',
        img: 'images/Minecraft-Xbox-One.jpg', 
        price: 29.99,
        category: 'games',
        stock: 18,
        description: 'Description of Minecraft',
        rating: 4.7,
        seller: 'Microsoft',
    },
    {
        id: '6',
        name: 'Nintendo Switch',
        img: 'images/Nintendo-Switch-OLED.jpg', 
        price: 349.99,
        category: 'consoles',
        stock: 6,
        description: 'Description of Nintendo Switch',
        rating: 4.1,
        seller: 'Nintendo',
    },
    {
        id: '7',
        name: "No Man's Sky",
        img: 'images/No-Mans-Sky-NS.jpg', 
        price: 29.99,
        category: 'games',
        stock: 7,
        description: "Description of No Man's Sky",
        rating: 3.9,
        seller: 'Hello Games',
    },
    {
        id: '8',
        name: 'Dark Souls II',
        img: 'images/Dark-Souls-II-Steam.jpg', 
        price: 39.99,
        category: 'games',
        stock: 5,
        description: 'Description of Dark Souls II',
        rating: 3.7,
        seller: 'Bandai',
    },
    {
        id: '9',
        name: 'Xbox Series S',
        img: 'images/Microsoft-Xbox-Series-S-Digital-Edition.jpg', 
        price: 299.99,
        category: 'consoles',
        stock: 4,
        description: 'Description of Xbox Series S',
        rating: 3.8,
        seller: 'Microsoft',
    },
    {
        id: '10',
        name: 'Xbox One',
        img: 'images/Microsoft-Xbox-One.jpg', 
        price: 149.99,
        category: 'consoles',
        stock: 3,
        description: 'Description of Xbox One',
        rating: 4.0,
        seller: 'Microsoft',
    },
    {
        id: '11',
        name: "Demon's Souls",
        img: 'images/Demons-Souls-PS5.jpg', 
        price: 59.99,
        category: 'games',
        stock: 5,
        description: "Description of Demon's Souls",
        rating: 4.6,
        seller: 'Sony',
    },
    {
        id: '12',
        name: 'Halo The Master Chief Collection',
        img: 'images/Halo-The-Master-Chief-Collection---Xbox-One.jpg', 
        price: 29.99,
        category: 'games',
        stock: 10,
        description: 'Description of Halo The Master Chief Collection',
        rating: 4.4,
        seller: 'Microsoft',
    },
    {
        id: '13',
        name: 'Halo Infinite',
        img: 'images/Halo-Infinite---Xbox-Series-X.jpg', 
        price: 54.99,
        category: 'games',
        stock: 11,
        description: 'Description of Halo Infinite',
        rating: 3.8,
        seller: 'Microsoft',
    },
    {
        id: '14',
        name: 'Spider-Man Miles Morales',
        img: 'images/Spider-Man-Miles-Morales.jpg',
        price: 22.99,
        category: 'games',
        stock: 7,
        description: 'Description of Spider-Man Miles Morales',
        rating: 4.3,
        seller: 'Sony',
    },
    {
        id: '15',
        name: 'PlayStation 4',
        img: 'images/Sony-PlayStation-4-Console.jpg',
        price: 249.99,
        category: 'consoles',
        stock: 6,
        description: 'Description of PlayStation 4',
        rating: 4.5,
        seller: 'Sony',
    },
    {
        id: '16',
        name: 'Meta Quest 2',
        img: 'images/Meta-Quest-2.jpg',
        price: 399.99,
        category: 'consoles',
        stock: 2,
        description: 'Description of Meta Quest 2',
        rating: 4.1,
        seller: 'Meta',
    },
    {
        id: '17',
        name: "Dragon's Dogma Dark Arisen",
        img: "images/Dragons-Dogma-Dark-Arisen---Nintendo-Switch.webp",
        price: 27.99,
        category: 'games',
        stock: 5,
        description: "Description of Dragon's Dogma Dark Arisen",
        rating: 4.4,
        seller: 'Capcom',
    },
    {
        id: '18',
        name: 'Flight Simulator',
        img: 'images/Flight-Simulator.webp',
        price: 37.99,
        category: 'games',
        stock: 8,
        description: 'Description of Flight Simulator',
        rating: 4.6,
        seller: 'Microsoft',
    },
    {
        id: '19',
        name: 'Pokemon Legends: Arceus',
        img: 'images/Pokemon-Legends-Arceus---Nintendo-Switch.webp',
        price: 59.99,
        category: 'games',
        stock: 6,
        description: 'Description of Pokemon Legends: Arceus',
        rating: 4.0,
        seller: 'Nintendo',
    },
    {
        id: '20',
        name: 'Sea of Thieves',
        img: 'images/Sea-of-Thieves---Xbox-One.webp',
        price: 18.99,
        category: 'games',
        stock: 11,
        description: 'Description of Sea of Thieves',
        rating: 3.9,
        seller: 'Microsoft',
    },
    {
        id: '21',
        name: 'Bloodborne',
        img: 'images/Bloodborne---PlayStation-4.webp',
        price: 19.99,
        category: 'games',
        stock: 7,
        description: 'Description of Bloodborne',
        rating: 4.7,
        seller: 'Sony',
    },
]

export const getProducts = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(products)
        }, 500)
    })
}

export const getProductById = (id) => {
    return new Promise((resolve => {
        setTimeout(() => {
            resolve(products.find(prod => prod.id === id))
        }, 500)
    }))
} 

export const getProductsByCategory = (categoryId) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(products.filter(prod => prod.category === categoryId))
        }, 500)
    })
}